source 'https://rubygems.org'

gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'dotenv-rails'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'puma', '~> 3.0'
gem 'rails', '~> 5.0'
gem 'sass-rails', '~> 5.0'
gem 'scrivito', '~> 1'
gem 'scrivito_advanced_editors'
gem 'secure_headers'
gem 'uglifier'
